# Generated by Django 5.2.5 on 2025-08-22 07:09

import new.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
                ('objects', new.models.CustomerUserManager()),
            ],
        ),
    ]
