# Generated by Django 5.2.5 on 2025-08-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_alter_customeruser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
            ],
        ),
    ]
